name: Docker Image CI

on:
  push:
    #branches: [ main ]  

jobs:

  Build-NewsClassifier:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker images and do docker-compose
      run: docker-compose up -d
