name: Docker Image CI

on:
  push:
    #branches: [ main ]  

jobs:

  Build-NewsClassifier:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker images and do docker-compose
      run: docker-compose build . --file docker-compose.yml --tag my-image-name:$(date +%s)
 
